### ISSUE TITLE
User settable ExifGlass transparency

### ISSUE THREAD

**Issue by daved163g** [d2phap/ExifGlass#10]
### Is your feature request related to a problem? Please describe.
It is almost impossible to read the Exif information on a semi-transparent panel.

### Describe the solution you'd like
Provide a user setable transparency level, or just the ability to turn it off altogether.

### Describe alternatives you've considered
unprintable

### Additional context
Would be useful to have the ESC key close the ExifGlass window, or maybe when you move the mouse off the ExifGlass window.

**Comment by d2phap** [comment]
@daved163g what version of ExifGlass are you using? on what OS version? Any screenshots?

ExifGlass 1.4 already fixed the transparency issue for Windows 10 as reported at #7

**Comment by daved163g** [comment]
So how are users supposed to know ExifGlass has been updated?

 

I will of course update it now.

**Comment by d2phap** [comment]
> So how are users supposed to know ExifGlass has been updated?

You can click on Menu > Check for update:

![image](https://github.com/d2phap/ExifGlass/assets/3154213/9fa0ddfc-50eb-40ac-a55c-30dca38ba1b5)
