### ISSUE TITLE
Hide categories such as numbers and TagIDs

### ISSUE THREAD

**Issue by Robot0005** [d2phap/ExifGlass#12]
I make the ExifGlass window small and scroll horizontally so that only TagName and TagValue are visible. By making it this size, you can check the Exif information without it overlapping with the 3:2 photo. 
![image](https://github.com/user-attachments/assets/a8f3f1e8-7e9d-45b9-83db-7c0f3a2358bb)

The downside to this is that the horizontal scroll position is reset every time you start ExifGlass again with the shortcut key. I thought it would be useful to have a setting to hide Tag ID, etc., or a setting to remember the scroll position.
![image](https://github.com/user-attachments/assets/c0c66219-c3cb-4a69-b10a-10e95ed0f662)

Also, if there was a setting to ungroup EXIF, Composite, File, etc., it would be convenient to be able to change the display order of the information.
![image](https://github.com/user-attachments/assets/6f3aaee3-9dba-43af-bed2-52ca82c7da1f)

Finally, I changed from the default photo viewer of Microsoft to imageGlass, exifglass, and it feels very good!

I am Japanese and I use translation. This is my first time posting on Github, so please point out if I am doing something inappropriate. Thank you!

**Comment by d2phap** [comment]
Hi @Robot0005,

To change the order, you need to manually enter the tag groups in the order you want.
For example: `--File:All --ExifTool:All -Composite:All -PNG:All`. This excludes "File" and "ExifTool" group, and put "Composite" before "PNG".
For details, you can check on their website: https://exiftool.org/#groups


About hiding columns, I will implement the feature to customize the columns in the next release.

**Comment by Robot0005** [comment]
@d2phap 
By reordering, I don't mean by groups, I mean if you want the ImageSize in the Composite group to appear below the CameraModel in the EXIF group, for example. It would be nice to be able to ungroup and hide the group name.
![Screenshot](https://github.com/user-attachments/assets/a4fd1316-d190-4c84-8188-89c68ab72f69)
I'm glad that column hiding will be implemented in the next release. Thanks!

**Comment by d2phap** [comment]
Changing columns is supported in [ExifGlass 1.7](https://github.com/d2phap/ExifGlass/releases/tag/1.7.0.0).

You can right-click on the column header to toggle the columns

**Comment by Robot0005** [comment]
It worked! Thank you so much!
![image](https://github.com/user-attachments/assets/605502f2-39de-456b-a393-e71903e77bac)
