### ISSUE TITLE
-- press ENTER -- problem

### ISSUE THREAD

**Issue by 7c9** [d2phap/ExifGlass#2]
![image](https://github.com/d2phap/ExifGlass/assets/49890604/2cbbbe9e-a19f-4117-9629-a94de790186c)

If the exiftool file name is **`exiftool(-k).exe`**, ExifGlass will keep outputting **`-- press ENTER --`**
Getting correct result after **change file name to `exiftool.exe`**
Don't know how, But it is possible to solve this problem temporarily.

**Comment by d2phap** [comment]
fixed this issue in [ExifGlass 1.2](https://github.com/d2phap/ExifGlass/releases/tag/1.2.0.0)
