### ISSUE TITLE
[Suggestion] Word Warp for Tag Value

### ISSUE THREAD

**Issue by pto2k** [d2phap/ExifGlass#5]
Hi,
For better viewing long text data, it would be nice to be able to toggle Word Warp for the Tag Value column.
With word warp, users could view the whole info at a glance without the need to scroll the table horizontally.

Example:
![Snipaste_2023-07-26_00-04-59](https://github.com/d2phap/ExifGlass/assets/4364117/4f044521-e9e1-44b3-bd92-75a6d243012d)

Thank you!

**Comment by d2phap** [comment]
Implemented in [ExifGlass 1.2](https://github.com/d2phap/ExifGlass/releases/tag/1.2.0.0)
