### ISSUE TITLE
Does this work with the static binary version of Exiftool?

### ISSUE THREAD

**Issue by hrxn** [d2phap/ExifGlass#6]
I'm just using the statically built Exiftool binary, i.e. `exiftool.exe` from the official Exiftool website, and I have it in my `%PATH%`.

Does this work with ExifGlass?

**Comment by d2phap** [comment]
In ExifGlass settings, you can add `exiftool` to the "Executable path" box, or full path of `exiftool.exe`.

![image](https://github.com/d2phap/ExifGlass/assets/3154213/773e2d93-b630-421b-ac1e-41982b051fe2)

**Comment by hrxn** [comment]
Thanks, that's what I wanted to know, perfect.
