### ISSUE TITLE
 TransparencyLevelHint="Mica" seems to be incompatible with Windows 10

### ISSUE THREAD

**Issue by Hammerliu** [d2phap/ExifGlass#7]
My OS version is Windows 10 22H2 19045.3693. When I open the ExifGlass, the background appears as a transparent color. After reading the source code, I discovered that when the TransparencyLevelHint property of the Window is set to 'Mica' and the Background is set to transparent  (in the file StyledWindow.cs), this issue occurs on Windows 10.

![rider64_rKeE4FH32v](https://github.com/d2phap/ExifGlass/assets/25999487/5f72b089-72eb-4700-aa76-aa7caee5afcd)

**Comment by d2phap** [comment]
Thanks @Hammerliu for the issue. It's fixed in [ExifGlass 1.4](https://github.com/d2phap/ExifGlass/releases/tag/1.4.0.0)
