### ISSUE TITLE
ExifGlass doesnt work

### ISSUE THREAD

**Issue by imTabber** [d2phap/ExifGlass#9]
I tried multiple photos but is always blank but only 1 time i get one error: 
assertion failed: open my_prog
assertion failed: MZ magic bytes
assertion failed: PE header
assertion failed: IMAGE_NT_OPTIONAL_HDR_MAGIC

System.Exception: assertion failed: open my_prog
assertion failed: MZ magic bytes
assertion failed: PE header
assertion failed: IMAGE_NT_OPTIONAL_HDR_MAGIC

   at ExifGlass.ExifTools.ExifTool.ReadAsync(String, CancellationToken , String[] ) in D:\_GITHUB\@d2phap\ExifGlass\Source\ExifGlass.Core\ExifTools\ExifTool.cs:line 100
   at ExifGlass.MainWindow.LoadExifMetadatAsync(String ) in D:\_GITHUB\@d2phap\ExifGlass\Source\ExifGlass.Core\MainWindow.axaml.cs:line 552

**Comment by d2phap** [comment]
Hi @ThomasGabber 
Can you send a screenshot or a video of steps to reproduce the error?

**Comment by imTabber** [comment]
https://github.com/d2phap/ExifGlass/assets/16322151/643df414-2614-4c1a-a27a-0c3d8fb9eedb

Purtroppo non so come replicarlo dato che mi è capitato solo una volta, praticamente ho aperto una foto ed e apparso on exifglass finestra.
Nel video mostro che lo screenshot non ha exif data ma lo fa con tutte le foto potrebbe eesere correlato con l'errore perche mi e capitato proprio testando varie foto.

**Comment by imTabber** [comment]
video uploud on google drive
https://drive.google.com/file/d/1lIdCC4tZ7SQHm2Z93k6gBP0lPi9sogk3/view

**Comment by d2phap** [comment]
Thanks @ThomasGabber for the video!
As I saw the Tools setting in ImageGlass for ExifGlass is missing `<file>` in argument column

![image](https://github.com/d2phap/ExifGlass/assets/3154213/3387b781-88eb-4950-a17f-f0dc5aa02345)

You can click on the pen icon to edit, and add `<file>` to the Argument textbox:

![image](https://github.com/d2phap/ExifGlass/assets/3154213/63ee7709-0447-43f6-b1f7-a0b4522bd71b)

**Comment by imTabber** [comment]
Added in argument but still no exif data shown
![Screenshot 2024-01-04 215556](https://github.com/d2phap/ExifGlass/assets/16322151/f666bfb6-518a-43b2-9da5-4d25efcdea72)
![Screenshot 2024-01-04 215608](https://github.com/d2phap/ExifGlass/assets/16322151/3d5564fe-4dc7-43bb-84e7-70de09528206)

**Comment by d2phap** [comment]
Hi @ThomasGabber 
- Do you have [exiftool](https://exiftool.org) installed on your machine?
- Can you try copying this command and run in Windows Terminal?
![image](https://github.com/d2phap/ExifGlass/assets/3154213/e0d0bf7a-a39b-4fb8-bb04-645ce2ebfa73)

**Comment by imTabber** [comment]
I had it in the system32 folder but now it's in the correctly folder and works. thanks for the support
